default_platform(:android)

platform :android do

  desc "Run Tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Build Debug APK"
  lane :build_debug do
    gradle(
      task: "assemble",
      build_type: "Debug"
    )
  end

  desc "Build Release APK"
  lane :build_release do
    gradle(
      task: "assemble",
      build_type: "Release"
    )
  end
end